spring.application.name=apollo-user
spring.datasource.url=jdbc:postgresql://localhost:5432/apollo-user
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lab.nan_contextual.creation=true