spring.application.name=${DB_APP_NAME}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=${DB_HIBERNATE_DDL_AUTO}

spring.jpa.properties.hibernate.jdbc.lab.nan_contextual.creation=true
spring.jackson.time-zone=America/Sao_Paulo
spring.datasource.hikari.data-source-properties.serverTimezone=America/Sao_Paulo
server.port=${SERVER_PORT}
api.security.token.secret=${JWT_SECRET:my-secret-key}

allowed.ip1=${ALLOWED_IP1}
allowed.ip2=${ALLOWED_IP2}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
